### ISSUE TITLE
Crash Course Slides and Tutorials

### ISSUE THREAD

**Issue by if4ww** [PIK-LPJmL/LPJmL#10]
Links appear in the _Home_ and _How _To__ Wikis for crash course power-point slides and tutorials. Clicking on either of these links, however, cycles the user back to the home page, without providing access to the named resources. 

Are the crash course power-point and tutorials available elsewhere? Thanks.

**Comment by cmueller-pik** [comment]
Sorry, these links were falsely copied into the wiki from the group-internal wiki at PIK. These slides are specific to the PIK environment and wouldn't help here. I've removed the misleading links

**Comment by if4ww** [comment]
Thank you, danke.  What is the procedure for seeking a collaboration with the Institute?  Ian From: Christoph MüllerSent: Thursday, October 15, 2020 11:20 AMTo: PIK-LPJmL/LPJmLCc: if4ww; AuthorSubject: Re: [PIK-LPJmL/LPJmL] Crash Course Slides and Tutorials (#10) Closed #10.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by cmueller-pik** [comment]
You can find contacts at the [PIK's LPJmL web site](https://www.pik-potsdam.de/en/institute/departments/activities/biosphere-water-modelling/lpjml/lpjml) and make contact with the sub-group most suitable for your proposal

**Comment by if4ww** [comment]
Thank you.  Ian From: Christoph MüllerSent: Thursday, October 15, 2020 12:54 PMTo: PIK-LPJmL/LPJmLCc: if4ww; AuthorSubject: Re: [PIK-LPJmL/LPJmL] Crash Course Slides and Tutorials (#10) You can find contacts at the PIK's LPJmL web site and make contact with the sub-group most suitable for your proposal—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
