### ISSUE TITLE
Error when enable -DUSE_JSON 

### ISSUE THREAD

**Issue by huangbinbin1993** [PIK-LPJmL/LPJmL#11]
Error happened when enabling '-DUSE_JSON' FLAG in the process of MAKE.   
The screen showed warnings： undefined reference to 'json_tokener_new' and others (like 'json_xxxx').
However, I have already installed 'JSON-c' package (https://github.com/json-c/json-c) in my Linux 

Would you mind give me some suggestions to solve this problem? Thanks.

**Comment by sostberg** [comment]
If you installed the `json-c` package through your package manager you may also need to specifically install the corresponding `dev` package. The main package only contains the library, not the header files.

**Comment by huangbinbin1993** [comment]
Yes, you are right. I have also installed the dev file. And I succeed to invoke it in the test.c file that I write. However, it needs to add some lines like ' -L/usr/local/lib/ -I/usr/local/include/json-c' to realize.  However, I still unknow how to add these lines in the Makefile or elsewhere in the process of MAKE.

**Comment by sostberg** [comment]
Please confirm that your `Makefile.inc` (generated by running `configure.sh`) contains a reference to the `json-c` library in the `LIBS =` line. If the library is installed in a standard location on your system, this should be achieved by adding `-ljson-c`

**Comment by huangbinbin1993** [comment]
Thank you very much for your help. Your suggestions are very useful! It worked to successfully finish the install.
