### ISSUE TITLE
Issue about soil input data

### ISSUE THREAD

**Issue by yjtw** [PIK-LPJmL/LPJmL#13]
I have a problem about the input data of soil. I see in the ./input_crumonthly.conf that there are two types of soil input data, which the one is ‘.bin’ and the other is ‘.descr’. I understand that the ‘.descr’ file is an interpretation file and the ‘.bin’ file is a data file. And I see in the description(https://gmd.copernicus.org/articles/11/1343/2018/) that the soil data is from HWSD. But there is no ‘descr’ file in the raw data of HWSD. The source of the ‘.descr’ file does not seem to be mentioned in the software package either. So I confused that how I could obtain the ‘grid.descr’ file? Looking forward to your reply, thank you very much.

**Comment by THRILLERLEMON** [comment]
Hello, can you provide your contact information? I'm a beginner from China. Maybe we can talk

**Comment by cmueller-pik** [comment]
We do not provide any support whatsoever as we have no capacities to do so.  
See [README](../blob/master/README)

**Comment by THRILLERLEMON** [comment]
Thank you for your reply

**Comment by yjtw** [comment]
> Thank you for your reply

I just noticed your reply. I am willing to communicate with you. My WeChat ID is hlk_ST.
