### ISSUE TITLE
Issue about NetCDF data

### ISSUE THREAD

**Issue by yjtw** [PIK-LPJmL/LPJmL#14]
I want to use the "cdf2" conversion tool in the bin directory to convert .nc files into .clm files, but I am prompted that this version is not supported. "ERROR401: NetCDF is not supported in this version of ./cdf2clm." What should I do? Looking forward to your reply, thank you very much.

**Comment by cmueller-pik** [comment]
Have a look at the code where that error message comes from. You will see that it's in the `#else` block of 
```ruby
#if defined(USE_NETCDF) || defined(USE_NETCDF4)
[...]
#else
  if(isout)
    fputs("ERROR401: NetCDF input is not supported by this version of LPJmL.\n",stderr);
  return NULL;
#endif
```
So you haven't compiled your code with the `-DNETCDF` or `-DNETCDF4` flag. Note that this will also require to include the corresponding header files and libraries. For that see also #12.

**Comment by zhengjiji456** [comment]
> I want to use the "cdf2" conversion tool in the bin directory to convert .nc files into .clm files, but I am prompted that this version is not supported. "ERROR401: NetCDF is not supported in this version of ./cdf2clm." What should I do? Looking forward to your reply, thank you very much.

Have you solved this problem?

**Comment by yjtw** [comment]
> > I want to use the "cdf2" conversion tool in the bin directory to convert .nc files into .clm files, but I am prompted that this version is not supported. "ERROR401: NetCDF is not supported in this version of ./cdf2clm." What should I do? Looking forward to your reply, thank you very much.
> 
> Have you solved this problem?

Sorry, I just read your message. I have solved it. You need to install the function library of NetCDF file under Linux system or virtual machine. If you don't understand the details, you can contact me. If you are Chinese, my wechat is hlk_ST。
