### ISSUE TITLE
cdf2soil

### ISSUE THREAD

**Issue by zhengjiji456** [PIK-LPJmL/LPJmL#16]
Hi, I tried this function to convert NetCDF data file into LPJ soil and coord data file, but failed with error message "NetCDF is not supported in this version". However, the function cru2clm could be used successfully.

**Comment by stenzelf** [comment]
You probably have not compiled the code with NETCDF support.
Please see the closed issues on this for help.

**Comment by sostberg** [comment]
As mentioned by the previous comment: If you check the code in src/utils/cdf2soil.c this error message is displayed when the code is compiled without NetCDF support.

**Comment by zhengjiji456** [comment]
Thanks. The problem has been solved.
