### ISSUE TITLE
Issue about input of soil

### ISSUE THREAD

**Issue by yjtw** [PIK-LPJmL/LPJmL#20]
Hello, I saw in the description that the soil uses the HWSD database in the wiki. However, there are 13 values in the soil parameter file, and there are more than 13 soil types in HWSD. How can I convert the soil information of HWSD into the soil file input of the LPJmL? I am looking forward to your reply.

**Comment by cmueller-pik** [comment]
I've just pushed the GGCMI processing script for HWSD data to github, which you can find [here](https://github.com/AgMIP-GGCMI/processing_hwsd_for_GGCMI), so that you can understand the data processing better.

**Comment by yjtw** [comment]
I am grateful for your reply.
