### ISSUE TITLE
How to convert the soil data

### ISSUE THREAD

**Issue by yjtw** [PIK-LPJmL/LPJmL#21]
Hello, I still haven't figured out the conversion method of soil input data. I see that according to the executable file cdf2soil, I should first obtain the soil data in NC file format. But the HWSD data uses the BIL and MDB formats. How should the conversion be completed?

**Comment by cmueller-pik** [comment]
The `cdf2soil` file is a helper function that you can, but don't have to use. See #20 for a link to the [GGCMI githup repository](https://github.com/AgMIP-GGCMI/processing_hwsd_for_GGCMI) with a script that converts the original HWSD to netCDF. Basically all you need is a vector of soil codes in the order of the grid.bin file that you use. If you are using 1-byte integer values, you don't need a [header](../wiki/input_header), which is the standard setup of soil code input.  
You can choose any way of producing that vector, no need to use the `cdf2soil` tool.
