### ISSUE TITLE
Issue about format of soil input data

### ISSUE THREAD

**Issue by yjtw** [PIK-LPJmL/LPJmL#22]
Thank you for your quick reply before, but it's embarrassing that I still haven't figured out the format of soil input data until now. My judgment is that the soil input data is a TXT text file (but input_example.html says it is in meta format), and the content is like this
"
1,8
2,6
3,11
4,2
...
"
The left column is the grid sequence, and the right column is the corresponding soil parameter number. The file is stored in txt with the suffix ‘’.descr‘’. I'm not sure if it's right. If possible, can you give a simple sign?

**Comment by sostberg** [comment]
There is an example `soil.descr` file in this issue #13.
The `soil.descr` simply describes the structure of the input file, it does not contain the values. The actual file containing soil codes for each grid cell is in binary format. It is referenced by the `file` attribute in the meta file.

**Comment by yjtw** [comment]
Thank you. 
So my understanding now is that soil input data can be converted by cdf2soil tool. Moreover, the input data in NC format is the longitude and latitude information and the attribute information of soil code, in which the soil code is 1-13. Is this correct?

**Comment by sostberg** [comment]
`cdf2soil` can be used to convert a NetCDF file containing soil codes into a binary input file. `cdf2soil` also creates a grid file. You do not need a `soil.descr` file to use the binary soil input file created by `cdf2soil`.
Make sure that the NetCDF uses the soil codes (1-13) as expected by LPJmL. The codes used by LPJmL differ from the USDA_TEX_CLASS codes used in HWSD.  `cdf2soil` will include all cells into the grid file and binary soil input file that contain non-missing values in the NetCDF. So make sure your soil NetCDF file covers all cells you want to simulate.

**Comment by yjtw** [comment]
Thanks for your reply! I think I have figured out this question!
