### ISSUE TITLE
When I **`make all`**, I get the following er

### ISSUE THREAD

**Issue by xfry-lixuan** [PIK-LPJmL/LPJmL#23]
When I **`make all`**, I get the following error and due to my stupidity, I spent the whole day without solving it. I hope you can tell me what the problem is and can let me solve it, thanks!

`readconfig.c(19): catastrophic error: cannot open source file "json-c/json.h"
  #include <json-c/json.h>
                          ^

compilation aborted for readconfig.c (code 4)
Makefile:75: recipe for target 'readconfig.o' failed
make[3]: *** [readconfig.o] Error 4
make[3]: Leaving directory '/home/.../LPJmL/src/lpj'
Makefile:54: recipe for target 'libs' failed
make[2]: *** [libs] Error 2
make[2]: Leaving directory '/home/..../LPJmL/src'
Makefile:50: recipe for target 'bin' failed
make[1]: *** [bin] Error 2
make[1]: Leaving directory '/home/.../LPJmL/src'
Makefile:53: recipe for target 'main' failed
make: *** [main] Error 2`

**Comment by cmueller-pik** [comment]
You need to have `json-c` installed on your system and the system needs to know where to find that installation.  
See e.g. https://stackoverflow.com/questions/17392380/include-json-c-in-c-project

Having said that, I just want to point out that we're incapable of providing support. Maybe you can find someone in your team to help you with IT issues.

**Comment by xfry-lixuan** [comment]
Thanks for your help, I will try to install `**json-c**` and fix it
