### ISSUE TITLE
When I make all ,I get this error : recipe for target 'utils' failed

### ISSUE THREAD

**Issue by xfry-lixuan** [PIK-LPJmL/LPJmL#24]
When I make all ,I get this error,but I can't fix it.
This is error reporting information:

`cru2cIm.o: In function 'main':
cru2clm.c:(.text+0x26): undefined reference to  "__intel new feature proc init"
../../lib/libtools.a(fwriteheader.o): In function  fwriteheader':
fwriteheader.c:(.text+0x35): undefined reference to "__intel_sse2 strlen"
collect2: error: ld returned 1 exit status
Makefile:210: recipe for target '../../bin/cru2clm' failed
make[1]: *** [../../bin/cru2clm] Error 1
make[1]: Leaving directory '/root/lpjml/LPImL/src/utils
Makefile:56: recipe for target 'utils' failed
make: *** [utils] Error 2`

**Comment by sostberg** [comment]
This does not seem to be related directly to LPJmL. A quick Google search suggests that it may be a problem with some versions of the Intel compiler. Unfortunately, we cannot provide support for that.

You may have better luck with the GNU C compiler.

**Comment by xfry-lixuan** [comment]
> 

Thank you
