### ISSUE TITLE
PFTs input

### ISSUE THREAD

**Issue by qyykk0520** [PIK-LPJmL/LPJmL#25]
Hi,
I wonder if I could change the coverage of PFTs by other data maps (e.g., the ESA-CCI). It seems the input data of land use in lpjml is only for cropland. Could you please guide me where or how can I make the adjustment for PFTs?
Many thanks.

**Comment by stenzelf** [comment]
Natural vegetation dynamically establishes, grows, and dies based on climatic and soil inputs and competition between the PFTs. https://doi.org/10.5194/gmd-11-1343-2018 
Prescribing it is not part of the model. If you want to do that, you'll need to modify the code.

**Comment by qyykk0520** [comment]
Okay I understand, thank you.

**Comment by qyykk0520** [comment]
Okay I understand, thank you.
