### ISSUE TITLE
Issue about new CFT

### ISSUE THREAD

**Issue by yjtw** [PIK-LPJmL/LPJmL#29]
Hello. I want to know, if I want to create new cft, what else is there to set besides establishing new parameters in pft.par? In other words, how are the bands and corresponding types of the input file of cft read? Looking forward to your answer, thank you!

**Comment by sostberg** [comment]
If you want to add a new CFT, you will also need a landuse input that includes growing areas for that CFT. We cannot provide personal support outside of joint collaborative agreements with PIK. 

However, we recently released a new software project called [LandInG](https://github.com/PIK-LPJmL/LandInG), the Land Input Generator, which can be used to create many of the input datasets that LPJmL needs. LandInG includes scripts to create landuse datasets. Even if you do not want to run LandInG yourself, it can give you an idea how input files need to be structured.

**Comment by yjtw** [comment]
Thank you for your answer and the supporting information! I would like to further elaborate on my question, I noticed that there are 16 types of cft mentioned in the https://github.com/PIK-LPJmL/LPJmL/wiki/Input#landuse. However, there are 15 types of cft+bft in the [pft.par file](https://github.com/PIK-LPJmL/LPJmL/blob/master/par/pft.par), and there is no such type as other crops. I did succeed following the 16 cft build when creating the land use input data. So I'm still confused about the cft and haven't figured out which code file I should refer to. I would be very grateful if you could answer my doubts.

**Comment by sostberg** [comment]
In this model version "other crops" are simulated together with "pasture/managed grass". They share a grassland stand that has the combined area fraction of other crops and pasture/managed grass.

**Comment by yjtw** [comment]
I understand. Thank you!
