### ISSUE TITLE
error: NetCDF input is not supported by this version of LPJmL.

### ISSUE THREAD

**Issue by qyy0520** [PIK-LPJmL/LPJmL#30]
Hi,

I got an error when trying to run the lpjml model with netCDF inputs. I have installed netCDF (version 4.8.1) and set environment variables in Ubuntu, somehow the model still reported: ERROR401: NetCDF input is not supported by this version of LPJmL.
Do you have any ideas how to solve this? I attached the running log down below.
Thank you so much.

==============================================================================
Simulation "LPJmL Run"
Simulation with fire, river routing, permafrost, new phenology.
Working directory: /mnt/d/research/models/lpjml4_linux/LPJmL
Starting from scratch.
Input files:
Variable   Fmt  Varname Filename
---------- ---- ------- ------------------------------------------------------
soil       raw          /mnt/d/research/models/lpjml4_linux/LPJmL/data/input/lpj_soil.bin
coord      clm2         /mnt/d/research/models/lpjml4_linux/LPJmL/data/input/lpj_grid.bin
temp       cdf  tas     /mnt/d/research/models/lpjml4_linux/LPJmL/data/input/lpj_tas_degC_5min.nc
prec       cdf  pr      /mnt/d/research/models/lpjml4_linux/LPJmL/data/input/lpj_pre_mm_5min.nc
lwnet      cdf  rlds    /mnt/d/research/models/lpjml4_linux/LPJmL/data/input/lpj_rlds_5min.nc
swdown     cdf  rsds    /mnt/d/research/models/lpjml4_linux/LPJmL/data/input/lpj_rsds_5min.nc
co2        txt          /mnt/d/research/models/lpjml4_linux/LPJmL/data/input/CO2_1990-2020.txt
drainage   clm2         /mnt/d/research/models/lpjml4_linux/LPJmL/data/input/drainage.bin
lakes      raw          /mnt/d/research/models/lpjml4_linux/LPJmL/data/input/lakes.bin
---------- ---- ------- ------------------------------------------------------

Writing restart file 'restart/restart_spinup.lpj' after year 1991.
No output files written.
Spinup years:                  3000
Cycle length during spinup:      30
First year:                    1991
Last year:                     1991
Number of grid cells:         24261

==============================================================================
ERROR401: NetCDF input is not supported by this version of LPJmL.
ERROR002: Initialization of input data failed, program terminated unsuccessfully.

**Comment by sostberg** [comment]
As explained in `INSTALL`  you need to set a compilation flag to enable NetCDF input/output. If you have installed the NetCDF library on your system (you also need the libnetcdf-dev package on Ubuntu), simply add the respective flag to the `LPJFLAGS=...` line in your Makefile.inc and compile the code.

**Comment by qyy0520** [comment]
I have included the flags in Makefile.inc (LPJFLAGS= -DSAFE -DUSE_RAND48 -DWITH_FPE -DUSE_NETCDF -DUSE_NETCDF4 -DUSE_UDUNITS ) and also installed the libnetcdf-dev package and did make, but still got the same error...

**Comment by sostberg** [comment]
Have you tried calling  `make clean`  before calling `make`  after you have changed Makefile.inc?

**Comment by qyy0520** [comment]
Ah yes, you are right, but when I did make clean and then called make, the lpjml in bin file disappeared. Did this ever happen?
