### ISSUE TITLE
ERROR197: text file is not supported for input '/mnt/f/.../co2_1861-2023.dat' in line 68 of 'input_crumonthly.conf' in this version of LPJmL.

### ISSUE THREAD

**Issue by qiumingliGit** [PIK-LPJmL/LPJmL#33]
Hello,

I got an error while trying to configure the CO2 data for the LPJml model on Ubuntu. Following the "input_crumonthly.conf" , I converted my co2-1861-2023.txt to co2-1861 -2023.dat and replaced the file path in the "input_crumonthly.conf": TXT /mnt/f/.../co2_1861-2023.dat.

However, . /bin/lpjml when the model reports the following: Reading configuration from 'lpjml.conf'.
ERROR197: text file is not supported for input '/mnt/f/... /co2_1861-2023.dat' in line 68 of 'input_crumonthly.conf' in this version of LPJmL.

Do you have any ideas how to solve this? I have attached the first few lines of my co2-1979-2023.dat below. Thank you very much.

YEARS CO2
1861  286.38
1862  286.50
1863  286.63
1864  286.78
1865  286.90
1866  287.00
1867  287.10

**Comment by stenzelf** [comment]
Remove the TEXT from your co2 file. It does not require a header.

**Comment by qiumingliGit** [comment]
I removed the table header, but it still shows ERROR197: text file is not supported for input '/mnt/f/... /co2_1861-2023.dat' in line 68 of 'input_crumonthly.conf' in this version of LPJmL. 

I checked my file format: file /mnt/f/.../co2_1861-2023.dat
/mnt/f/.../co2_1861-2023.dat: ASCII text

After removing, the first few lines of input '/mnt/f/... /co2_1861-2023.dat' look like this: 
1861  286.38
1862  286.50
1863  286.63
1864  286.78
1865  286.90

I also tried removing the year information, but it still shows the same ERROR197.
286.38
286.5
286.63
286.78
286.9

**Comment by cmueller-pik** [comment]
you will need the column with years in the input file.   
But we need a little more context here. In this version of the code, there's a multitude of different configuration files and if you're using `input.conf` you may also be using some `lpjml.conf` variant.    
Upcoming versions of LPJmL (to be posted here) will be stripped of many of these configuration files as this causes confusion.  
Generally, the `conf` files are very sensitive to the sequence (and number) of elements listed and it is strongly advised to use the `json` based files ending with `.js` for configuring your simulation.   
Per default, I would recommend to use `lpjml.js` to start of with, which `#include`s `input_crumonthly.js` for input.
