### ISSUE TITLE
ERROR249: Number of cells in grid file '/mnt/e/Sofeware/Productivity/lpjml_0310/LPJmL-5.7.5/input/grid.bin'=67420 less than 67471.

### ISSUE THREAD

**Issue by qiumingliGit** [PIK-LPJmL/LPJmL#34]
Hello,

I got an error while trying to configure lpjml.js for the LPJml 5.7.5 model on Ubuntu.  All input files were derived from the recommended LandInG model output. All .bin files should have a raster cell count of 67420. 

However, the configuration produces the following output. I am not sure how the number 67471 was generated. Do you know how to solve it? Thank you very much for your reply!

./bin/lpjml lpjml.js
******************************************************************************
****         _     ____     _           _       ____        _____         ****
****        | |   |  _ \   | |_ __ ___ | |     | ___|      |___  |        ****
****        | |   | |_) |  | | '_ ` _ \| |     |___ \         / /         ****
****        | |___|  __/ |_| | | | | | | |___   ___) |  _    / /          ****
****        |_____|_|   \___/|_| |_| |_|_____| |____/  (_)  /_/           ****
****                                                                      ****
****                 lpjml C Version 5.7.5 (Mar 10 2024)                  ****
****    Dynamic global vegetation model with natural and managed land     ****
****                     Compiled for Linux with MPI                      ****
****       (C) Potsdam Institute for Climate Impact Research (PIK),       ****
****                          see COPYRIGHT file                          ****
****              Authors, and contributors see AUTHORS file              ****
**** This version of LPJmL is licensed under GNU AGPL Version 3 or later  ****
****        See LICENSE file or go to http://www.gnu.org/licenses/        ****
****                 or invoke lpjml -l to print license                  ****
****             Contact: https://github.com/PIK-LPJmL/LPJmL              ****
****                                                                      ****
******************************************************************************

Running for user   on   at Tue Mar 12 22:02:13 2024
Reading configuration from 'lpjml.js'.
WARNING036: 'soilmap' not defined for soil type 'clay (light)'.
==============================================================================
Simulation "LPJmL Run"
Simulation with land fraction read from file, random precipitation,
shuffle spinup climate, river routing, with lakes, equilsoil is called,
permafrost, Johansen conductivity, GSI phenology.

Working directory: /mnt/.../LPJmL-5.7.5
Starting from scratch.
Input files:
Variable     Fmt  Filename
------------ ---- -------------------------------------------------------------
soil         raw  /.../soil.bin
coord        clm  /.../grid.bin
landfrac     clm  /.../landfrac.bin
temp         clm  /.../cru_ts4.07.1901.2022.tmp.dat.clm
prec         clm  /.../cru_ts4.07.1901.2022.pre.dat.clm
cloud        clm  /.../cru_ts4.07.1901.2022.cld.dat.clm
co2          txt  /.../co2_1861-2023.dat
wetdays      clm  /.../cru_ts4.07.1901.2022.wet.dat.clm
lakes        raw  /.../glwd_lakes_and_rivers.bin
drainage     clm  /.../drainage_stn.bin
------------ ---- -------------------------------------------------------------
Writing restart file 'restart/restart_1840_nv_stdfire.lpj' after year 1840.
Random seed: 2
Number of output files:       1
Output written in year:       -1599
Byte order in output files:   little endian

Variable   Fmt  Unit Type  dt  nbd Filename
---------- ---- ---- ----- --- --- --------------------------------------------
globalflux txt  -    float Y     1 output/globalflux_spinup.csv + .json
---------- ---- ---- ----- --- --- --------------------------------------------
Spinup years:                  3500
Cycle length during spinup:      30
First year:                    1901
Last year:                     1901
Number of grid cells:         67471
==============================================================================
ERROR249: Number of cells in grid file '/.../grid.bin'=67420 less than 67471.
ERROR003: Initialization of LPJ grid failed, program terminated unsuccessfully.

**Comment by cmueller-pik** [comment]
as you can see from the `number of grid cells: 67421` line you are specifying that you want to run the model for 67421 cells, yet the inputs only have 67420.  
Please note that the indexing in C starts with 0. 
You can use the keyword `"all"` if you simply want to run for all cells included in the input data:
```ruby
  "startgrid" : "all", 
  "endgrid"   : "all",
```
if you want to be explicit, it should be
```ruby
  "startgrid" : 0, 
  "endgrid"   : 67419,
```
If you're using the `"all"` keywording, there must be a file that specifies 67421 input grid cells, probably the soil data (which I think are the first data to be read). It can be wrong in the header of the files or the number of records.

**Comment by qiumingliGit** [comment]
Thank you very much for your reply! I found the solution. I used LandInG to form the input soil.bin data. When configuring input_crumonthly.js, I should specify the file type as "clm". i.e. "soil" : { "id" : 41, "fmt" : "clm", "name" : "soil.bin"},
