### ISSUE TITLE
ERROR038: Cloudiness=-11232.9% not in [0,100] for cell 0 at day 1, program terminated unsuccessfully.

### ISSUE THREAD

**Issue by qiumingliGit** [PIK-LPJmL/LPJmL#35]
Hello,

I got an error while trying to use ./bin/cru2clm to convert cru.dat files to .clm files. All cru.dat  files were derived from CRU TS Version 4.07. 

I used the following command to convert the cru.dat files:
./bin/cru2clm -firstyear 1901 -lastyear 2022 -nyear 102 -ncell 67420 /mnt/...cru/cru_ts4.07.1901.2022.cld.dat /mnt/.../cru_ts4.07.1901.2022.cld.dat.clm
./bin/lpjml lpjml.js:
ERROR038: Cloudiness=-11232.9% not in [0,100] for cell 0 at day 1, program terminated unsuccessfully.

I also tried to use the following command to convert the cru.nc files:
./bin/cru2clm -firstyear 1901 -lastyear 2022 -nyear 102 -ncell 67420 /mnt/...cru/cru_ts4.07.1901.2022.cld.dat.nc /mnt/.../cru_ts4.07.1901.2022.cld.dat.nc.clm
.bin/lpjml lpjml.js:
ERROR038: Cloudiness=10372.5% not in [0,100] for cell 1 at day 1, program terminated unsuccessfully.

How should I convert the cru files correctly? Thank you very much for your reply!

**Comment by cmueller-pik** [comment]
If you look into the `man pages` of that function
```
man cru2clm
```
you'll see that it assumes a 16-byte integer in the original data, maybe check if that's the case?
If you want to convert netCDF files, you'd have to use `cdf2clm`.  
Again, check
```
man cdf2clm
```

for details.
