### ISSUE TITLE
input soil data as nc format

### ISSUE THREAD

**Issue by qyykk0520** [PIK-LPJmL/LPJmL#36]
Hello,
I understand there have been many questions related to soil input, but I still wonder is it not supportable for using netcdf format as soil input but only binary? 
I tried to command `CDF stxt data/soiltexture.nc` but the model reported errors:
ERROR197: Only text file is supported for CO2 input in this version of LPJmL.
ERROR001: Cannot read configuration, program terminated unsuccessfully.
But when I used the binary format everything was fine.
 
Thank you.

**Comment by qyykk0520** [comment]
Thank you! I will try `json` for configuration again. The `stxt` is the varname I used for the `soiltexture.nc` file. If you don't mind, I also wanna ask if I should set the data type of  `soiltexture.nc` to char instead of integer or double?

**Comment by cmueller-pik** [comment]
I guess it doesn't matter for `cdf` input, but I don't know.
