### ISSUE TITLE
QUESTIONS ABOUT INPUT DATA 

### ISSUE THREAD

**Issue by weiuser1** [PIK-LPJmL/LPJmL#37]
I am currently learning to use the LPJmL model, but I'm not very clear on how to write its input data. I hope someone can help guide me. Thank you.

**Comment by weiuser1** [comment]
Thank you for your response, but I still have some doubts. Is there a user manual available for using this tool, and are there reference examples for inputting climate data?

**Comment by sostberg** [comment]
The LandInG toolbox includes readme files for each type of input. Besides that, the toolbox is documented in the paper I linked. And the code itself is commented. There is no specific user manual on top of that.
For climate inputs there are some conversion tools included in the LPJmL code. They are built with `make utils`. Essentially, climate inputs need to be monthly or daily time series of the climate variables LPJml needs, in the units required by LPJmL. So you may need to do a unit conversion in pre-processing. For daily climate inputs, you also need to be aware that LPJmL does not support leap years. So if your source data include leap years you need to remove these additional days to get 365 days in all years.

**Comment by weiuser1** [comment]
Thank you, I understand now. Do you have any good resources for learning about preparing climate data?

**Comment by weiuser1** [comment]
I see.Thank you!
