### ISSUE TITLE
Error message with land use nc input

### ISSUE THREAD

**Issue by qyykk0520** [PIK-LPJmL/LPJmL#38]
Hello,
Sorry bother again. I met a strange problem that confused me for a while.  I tried to use nc format as input. I tried to created a continuous land use netcdf data as input. The time series was from 2000 to 2015 and the started time was defined from 2000. I replaced all NA values with 0.  The model recognized this input, as the message “simulation begins” popped up, but then followed with an error message that “Missing value for cell=0”. I tried several times with cropped regional data or the global data but all showed the similar error message. I am not sure if it because the model cannot match the lon/lat information and so missed the values. This situation never happened in creating climate data.
I attached my running logs. Thanks in advance.

[landuse netcdf error.txt](https://github.com/PIK-LPJmL/LPJmL/files/14921782/landuse.netcdf.error.txt)

**Comment by cmueller-pik** [comment]
Hi, looks like your grid file (in `clm` format) contains coordinates for cell index 0 that has no data in your land-use input file. Check your `data/input/YRB_cropfrac_2000-2015_startime_test.nc` for the coordinates given by the error message `35.88N 91.38E`

**Comment by sostberg** [comment]
If you say above that you replaced NA values with 0 make sure that you did not accidentally set the missing value attribute to 0 in the metadata of the NetCDF file. LPJmL checks for the missing value attribute that's defined in the NetCDF file.
