### ISSUE TITLE
files for wiki

### ISSUE THREAD

**Issue by cmueller-pik** [PIK-LPJmL/LPJmL#4]
Seems like the st*@id github wiki does not allow for adding attachments to wiki pages, except for images.
A workaround is proposed to attach files to issues, which works, and then link to files from the wiki to that issue.   
So this is the issue that hosts all files needed in the wiki.
Sigh.
And github only allows a very limited set of file types. So the CSV tables are stored as txt here.
Sigh. Sigh.

[LPJ_CellBelongingsToCountries.txt](https://github.com/PIK-LPJmL/LPJmL/files/2244134/LPJ_CellBelongingsToCountries.txt)

[CountriesToCellsManual.pdf](https://github.com/PIK-LPJmL/LPJmL/files/2244123/CountriesToCellsManual.pdf)

[fpar_maize](https://user-images.githubusercontent.com/11943892/44329755-97c93c00-a465-11e8-9cbb-e3902ec3218b.png)

**Comment by slshi9705** [comment]
My computer cannot complete the following steps during the LPJmL configuration process, how can I solve this problem?
![47284a2237e7dbc677a757d16f9ea06](https://github.com/PIK-LPJmL/LPJmL/assets/129734193/e54f4029-9cb3-475a-903c-005a29f45dcf)

**Comment by sostberg** [comment]
Loading these modules is only relevant if you run LPJmL on the PIK high performance cluster. On other systems you need to make sure that all required external libraries are installed and can be found by the compiler.

Please note that this issue is not the place to ask questions.
