### ISSUE TITLE
How to setup the LPJmL model for high spatial resolution simulations

### ISSUE THREAD

**Issue by qiumingliGit** [PIK-LPJmL/LPJmL#40]
Hello, does the LPJmL model support for high spatial resolution simulations? What is the highest supported resolution?
Thank you very much for your reply!

**Comment by sostberg** [comment]
The spatial resolution depends mostly on the resolution of the input. That means that if you provide all inputs at a finer resolution, the model is technically able to run at that resolution.
However, note that some of the assumptions in the river routing scheme may no longer be valid at higher resolutions.
