### ISSUE TITLE
Incompatible pointer type in fscanpftpar.c:

### ISSUE THREAD

**Issue by LukasvdWiel** [PIK-LPJmL/LPJmL#42]
I am trying to compile your impressive abbreviation with gcc (GCC) 14.1.0

and I get a compile time error:

mpicc -Wall -m64 -DUSE_RAND48 -DUSE_MPI -DSAFE -DWITH_FPE -DUSE_NETCDF -DUSE_UDUNITS -DPERMUTE  -O3 -I../../include -c fscanpftpar.c
fscanpftpar.c: In function ‘fscanpftpar’:
fscanpftpar.c:171:51: error: passing argument 4 of ‘fscankeywords’ from incompatible pointer type [-Wincompatible-pointer-types]
  171 |     if(fscankeywords(item,&pft->type,"type",config->pfttypes,config->ntypes,FALSE,verb))
      |                                             ~~~~~~^~~~~~~~~~
      |                                                   |
      |                                                   char **

GCC 11.4 is more forgiving, so it is not really urgent, but for future proofing the pointers will need looking at.

**Comment by sostberg** [comment]
Thanks for the notice. The development version of LPJmL at PIK is currently in the process of transitioning to a new high-performance computer with newer compiler versions. As part of this transition, the development team has changed the handling of compiler warnings and fixed many small code issues. The next release of LPJmL on Github will most likely include these changes.
