### ISSUE TITLE
Old MPI calls that are no longer valid detected

### ISSUE THREAD

**Issue by LukasvdWiel** [PIK-LPJmL/LPJmL#43]
I am compiling with openMPI 4.1.4, which is already a bit old-ish.
It used the MPI 3.0 standard: https://www.mpi-forum.org/docs/mpi-3.0/mpi30-report.pdf
The 3.0 standard has been introduced in 2012... so it not exactly as if we are riding the bleeding edge here.

In MPI 3.0 some commands have been replaced by more intuitive ones.
A list can be seen here: https://www.open-mpi.org/faq/?category=mpi-removed

MPI_Type_extent has been replaced by MPI_Type_get_extent

It can be found in several places in LPJmL:

(10:44 lukas@login01 LPJmL-5.7.9) > grep -ri 'MPI_Type_extent'
src/netcdf/mpi_write_netcdf.c:  MPI_Type_extent(type,&extent);
src/netcdf/mpi_write_pft_netcdf.c:  MPI_Type_extent(type,&extent);
src/pnet/pnet_setup.c:  MPI_Type_extent(pnet->type,&extent); /* calculate size of datatype */
src/socket/mpi_read_socket.c:  MPI_Type_extent(type,&extent);
src/socket/mpi_write_socket.c:  MPI_Type_extent(type,&extent);
src/tools/mpi_write.c:  MPI_Type_extent(type,&extent);
src/tools/mpi_write_txt.c:  MPI_Type_extent(type,&extent);

The difference in arguments is that MPI_Type_get_extent includes a lower bound, while MPI_Type_extent did not.
More about it here: https://www.open-mpi.org/doc/current/man3/MPI_Type_get_extent.3.php

I cannot really easily see what those lower bounds should be, but perhaps you can have a look at it.

Much appreciated and enjoy the weekend!

Lukas

**Comment by sostberg** [comment]
Thanks for the notice. The development version of LPJmL at PIK is currently in the process of transitioning to a new high-performance computer with newer compiler versions. As part of this transition, `MPI_Type_extent` has been replaced with `MPI_Type_get_extent`. The next release of LPJmL on Github will most likely include these changes.

**Comment by LukasvdWiel** [comment]
Hi Sostberg,

thank you for your quick reaction!
I am trying the development version now, and the MPI calls there are still the old ones.
See line 33 of : https://github.com/PIK-LPJmL/LPJmL/blob/master/src/tools/mpi_write.c  for example.

I am checking the master branch. Is there perhaps a different branch that already has the MPI calls fixed, that I may try?

Cheers and thanks
Lukas

**Comment by sostberg** [comment]
The version including these fixes is not available on Github yet.

**Comment by LukasvdWiel** [comment]
In that case, do you have any recommendations on how I get LPJml working?
What compiler/mpi version do you use yourself?

I am now trying to install openMPI 1.3.4, from 2009, which is the most recent version from before the MPI 3 standard, but that in turn has all kinds of sloppy programming in it that are no longer allowed in GCC 11.4, which is the oldest version we have after an OS upgrade to CentOS 7 (which went end of life a month ago) to Rocky Linux 9. :-\

And pointer (pun intended) is appreciated.

Lukas

**Comment by sostberg** [comment]
As stated in the README, we cannot provide support outside of joint collaborative agreements with PIK. Getting different compilers and MPI versions to work together can be a bit tricky. The version available on Github has configuration files that we know to work with Intel version 15.0.3 and Intel MPI version 5.1.3. It uses `icc` and `mpiicc` 
The current development version (that is not available on Github yet) uses Intel OneAPI 24.0.0 (`icx` and `mpiicx`)

Since you work at Utrecht University (according to your Github profile) consider contacting the IMAGE team at Utrecht University for support. IMAGE uses a version of LPJmL and the team may have experience getting the model to run on your system.

**Comment by cmueller-pik** [comment]
I've pushed version [5.9.7](https://github.com/PIK-LPJmL/LPJmL/releases/tag/v5.9.7) to github, which should include all the changes to a newer MPI and changes to no longer have compiler warnings. Default is to compile with the flag `-Werror` which throws an error for each warning.   
Hope that makes things easier for you.  
Thanks @sostberg for detailed responses!

**Comment by LukasvdWiel** [comment]
Thanks a lot!

That is indeed a great help!
I had to turn -Werror off, but I am getting a lot further.

I am fixing some of the dependencies now, but I am confident I will get it
to work.

Also I will look if I can find this IMAGE team you mentioned.
Our researcher requesting LPJmL has also not heard of them, so it might be
useful to get in touch.

Have an excellent weekend and thanks again,

Lukas

**Comment by cmueller-pik** [comment]
With the back and forth between gitlab and github I made several strategic mistakes in setting things up and back then I had reintroduced a lot of previously deleted files. I have corrected that now (under the same version tag) so you may want to pull a fresh copy. 
Sorry for the hassle.
The IMAGE Team is at PBL.nl where they run LPJmL within the integrated assessment model IMAGE. Some of them are also affiliated with Utrecht University, I think, but maybe not those who work with LPJmL there.

**Comment by LukasvdWiel** [comment]
Thank you for letting me know!

I have pulled a fresh version and it compiled smoothly!

I am indeed at Utrecht University, Earth Sciences department.

Cheers
Lukas
