### ISSUE TITLE
A small example is required

### ISSUE THREAD

**Issue by wk1984** [PIK-LPJmL/LPJmL#5]
It's better to put a small example here in any supported format, netCDF, binary, etc. That will be much more useful for the users who only want to prepare their own inputs to make a quick start. May one or two pixels are enough. Or make a bash script to download CRU dataset?

**Comment by cmueller-pik** [comment]
Have a look at the `src/utils` folder, where you find e.g. the file [cru2clm.c](../blob/master/src/utils/cru2clm.c) which converts the CRU data to the LPJmL specific input format, including the header.
That is hopefully self-explaining enough. Also, have a look at the `man pages`, the [input_header](../wiki/input_header) and [Adding_new_input_files](../wiki/Adding_new_input_files) wiki pages.
