### ISSUE TITLE
Could I download LPJml for my own research

### ISSUE THREAD

**Issue by WYPZL** [PIK-LPJmL/LPJmL#6]
This question seems a bit silly. Could I download LPJml for my own research and publish an article? Or is it necessary to sign an agreement with PIK?

**Comment by cmueller-pik** [comment]
Thanks for your interest.
You're free to download the source code and are free to do research and publish articles, based on that work with the LPJmL model. The source code is subject to the [AGPL license](https://www.gnu.org/licenses/agpl.txt). 
We only request signing a contract on passing on the user rights to PIK if you want to commit code to this repository and have it part of the central LPJmL code.
For more details see the LICENSE file.

**Comment by Damonfruit** [comment]
I also wanna know...




On 01/07/2019 19:27, WYPZL wrote:

This question seems a bit silly. Could I download LPJml for my own research and publish an article? Or is it necessary to sign an agreement with PIK?
