### ISSUE TITLE
compiled in VS2015 warning that can not find advapi32.lib & ws2_32.lib. Meanwhile , could you please give a completed dataset file for guiding users  to operate this model ,or it will cause confusing. Thank you very much!

### ISSUE THREAD

**Issue by liwei1993abc** [PIK-LPJmL/LPJmL#7]

**Comment by cmueller-pik** [comment]
This is a problem of how you have configured your visual studio.
We cannot provide support on that, a [quick google search produced this similar problem](https://stackoverflow.com/questions/35144609/include-not-finding-library-in-visual-studio-2015), maybe that helps.
As specified in the wiki, we're unable to provide input data which are not ours to distribute.
There are various helper programs in "utils" that should help you to produce the files.
Again, we cannot provide support outside joint (funded) collaborations.
cheers
Christoph
