### ISSUE TITLE
Cannot open file '/p/projects/....../soil.descr'

### ISSUE THREAD

**Issue by CPTBTPTP-bit** [PIK-LPJmL/LPJmL#8]
I am a beginner. I don't know what is soil.descr. Where is the soil data used by LPJmL coming from? And there is no config file for Mexico in the wiki, when you open **Mexico.conf, it is empty. How can I get started with LPJmL quickly? Looking forward to your reply. Thanks.

**Comment by cmueller-pik** [comment]
all paths specified in the wiki are just examples and not accessible outside PIK's computation infrastructure. Sorry for the confusion.  
We're not supplying any support outside agreed (and funded) research collaboration.
We're not supplying any input data as those are not owned by PIK.   
The _utils_ programs provide some help in generating input files.

**Comment by CPTBTPTP-bit** [comment]
Thanks

**Comment by slshi9705** [comment]
I am a beginner in LPJmL, and when I was simulating, the following error occurred. How should this problem be solved
![e0309b9d3b93811332e9060ab795287](https://github.com/PIK-LPJmL/LPJmL/assets/129734193/68779518-3bdc-453b-ac73-452842fd7043)

**Comment by sostberg** [comment]
The error message informs you about a missing model input file. The LPJmL release does not include any model input files, such as the mentioned `soil.descr`. You will have to create all required input files yourself and then update paths to these files in the LPJmL confiiguration. Note that we cannot provide any support outside agreed (and funded) research collaborations, as mentioned in the earlier comment.

However, we have recently released a new toolbox that can be used to create inputs for LPJmL: https://github.com/PIK-LPJmL/LandInG

**Comment by slshi9705** [comment]
I have another problem, my computer can not complete the following process during the configuration of the LPJmL model. Does this affect the operation of LPJmL? If so, how can the problem be resolved?






静静看着凌晨黄昏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PIK-LPJmL/LPJmL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月21日(星期五) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PIK-LPJmL/LPJmL] Cannot open file '/p/projects/....../soil.descr' (#8)





 
The error message informs you about a missing model input file. The LPJmL release does not include any model input files, such as the mentioned soil.descr. You will have to create all required input files yourself and then update paths to these files in the LPJmL confiiguration. Note that we cannot provide any support outside agreed (and funded) research collaborations, as mentioned in the earlier comment.
 
However, we have recently released a new toolbox that can be used to create inputs for LPJmL: https://github.com/PIK-LPJmL/LandInG
