### ISSUE TITLE
issue in setting up the model

### ISSUE THREAD

**Issue by muditsrivastava073** [PIK-LPJmL/LPJmL#9]
As I was installing the LPJmL model in my local (ubuntu) and according to the method mentioned [here](https://github.com/PIK-LPJmL/LPJmL/wiki/HowTo) I tried running the configure.sh file and found this error

`mudit@mudit-ubuntu:~/Documents/LPJmL$ ./configure.sh
Configuring LPJmL 4.0.002...
No input directory found, LPJINPATH has to be set
Operating system is Linux
Create executables with make all
Put . /home/mudit/Documents/LPJmL/bin/lpj_paths.sh in your /home/mudit/.profile
`

even after writing the contents of lpj_paths.sh in .profile I still have the same error. Did I do something wrong? Can anyone help me in setting up the model on my laptop?

**Comment by sostberg** [comment]
This is not an error of `configure.sh`. The script seems to have finished successfully. The script is only telling you that it cannot detect an input directory automatically so you have to set it in `lpj_paths.sh` with `export LPJINPATH=path_to_your_input_files`.

Note that the download from Github includes only the model code, no input data. You will have to create all input data yourself. See the note regarding input data but also regarding technical support in the README file included in your download.

**Comment by muditsrivastava073** [comment]
ok, thanks. I also executed the `configure.sh` command without executing the `module load lpjml` command. as on executing the latter, it shows `module: command not found` error. Will it be a problem if I proceed without executing the latter command? I know this error is something not related to LPJmL and is system-specific. Can you help me out with this also?

**Comment by sostberg** [comment]
The `module load lpjml`  is specific to running LPJmL on the high performance computer at PIK where it was developed. You don't need this on Ubuntu.

**Comment by LongfeiZhan** [comment]
> As I was installing the LPJmL model in my local (ubuntu) and according to the method mentioned [here](https://github.com/PIK-LPJmL/LPJmL/wiki/HowTo) I tried running the configure.sh file and found this error
> 
> `mudit@mudit-ubuntu:~/Documents/LPJmL$ ./configure.sh Configuring LPJmL 4.0.002... No input directory found, LPJINPATH has to be set Operating system is Linux Create executables with make all Put . /home/mudit/Documents/LPJmL/bin/lpj_paths.sh in your /home/mudit/.profile `
> 
> even after writing the contents of lpj_paths.sh in .profile I still have the same error. Did I do something wrong? Can anyone help me in setting up the model on my laptop?

I encountered the same problem. Do you successfully run the model later?

**Comment by cmueller-pik** [comment]
Have a look at the configure.sh script to see what it does. These messages tell you different things. Also have a look at html/lpjml.html for the meaning of LPJINPATH

**Comment by muditsrivastava073** [comment]
> > As I was installing the LPJmL model in my local (ubuntu) and according to the method mentioned [here](https://github.com/PIK-LPJmL/LPJmL/wiki/HowTo) I tried running the configure.sh file and found this error
> > `mudit@mudit-ubuntu:~/Documents/LPJmL$ ./configure.sh Configuring LPJmL 4.0.002... No input directory found, LPJINPATH has to be set Operating system is Linux Create executables with make all Put . /home/mudit/Documents/LPJmL/bin/lpj_paths.sh in your /home/mudit/.profile `
> > even after writing the contents of lpj_paths.sh in .profile I still have the same error. Did I do something wrong? Can anyone help me in setting up the model on my laptop?
> 
> I encountered the same problem. Do you successfully run the model later?

Actually, after installing the model I started to work on the input data sets. So I haven't run the model yet.

**Comment by hnlyj** [comment]
I think you should put the input data set in the code for easy reference

**Comment by cmueller-pik** [comment]
We don't provide input data as these are not ours and may be subject to license restrictions. See [the input wiki page](https://github.com/PIK-LPJmL/LPJmL/wiki/Input).  
After compilation with `make all` you will also have some utility tools in the `bin/` folder for helping you with generating your own input data sets.

**Comment by hnlyj** [comment]
Thank you very much for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Christoph ***@***.***&gt;; 
发送时间: 2021年4月25日(星期天) 凌晨1:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PIK-LPJmL/LPJmL] issue in setting up the model (#9)





 
We don't provide input data as these are not ours and may be subject to license restrictions. See the input wiki page.
 After compilation with make all you will also have some utility tools in the bin/ folder for helping you with generating your own input data sets.

**Comment by hnlyj** [comment]
Dear Christoph Müller
I'm an undergraduate and recently I'm interested in your team's LPJ model. It took a day to compile the code&nbsp;successfully. Due to my stupidity, I still couldn't understand how to use the document correctly. If you can send me the input data of the code, this will save a lot of time for me. My mother tongue is not English. Please forgive me if I can't express it 。
My email address is ***@***.*** and I will be looking forward to your reply。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Christoph ***@***.***&gt;; 
发送时间: 2021年4月25日(星期天) 凌晨1:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PIK-LPJmL/LPJmL] issue in setting up the model (#9)





 
We don't provide input data as these are not ours and may be subject to license restrictions. See the input wiki page.
 After compilation with make all you will also have some utility tools in the bin/ folder for helping you with generating your own input data sets.

**Comment by huangsiyr** [comment]
dear cmueller-pik,
I also encounted such problem in centos8 with gcc (GCC) 8.5.0 20210514. I have set the LPJROOT=/HOME/lpjml-workstation/LPJmL and the LPJINPATH=HOME/lpjml-workstation/LandInG, it also shows that ./configure.sh 

Configuring LPJmL 5.9.7...
No input directory found, LPJINPATH has to be set
Operating system is Linux
MPICH found
Create executables with make all
Put . /HOME/lpjml-workstation/LPJmL/bin/lpj_paths.sh in your /HOME/.profile


AND when I run make && make all, it shows that  
`mpicc -Wall -m64 -DUSE_RAND48 -DUSE_MPI -DSAFE -DWITH_FPE -DUSE_NETCDF -DUSE_UDUNITS -DPERMUTE -DSTRICT_JSON  -Werror -O3 -I../../include -c establishmentpft.c
establishmentpft.c: 在函数‘establishmentpft’中:
establishmentpft.c:85:53: 错误：此函数中的‘fpc_obs’在使用前可能未初始化 [-Werror=maybe-uninitialized]
         (stand->prescribe_landcover == LANDCOVEREST && fpc_obs > 0 &&  pft->par->cultivation_type==NONE && stand->type->landusetype==NATURAL) ||
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
cc1：所有的警告都被当作是错误
`
here attach my Makefile.inc

`CC      = mpicc
DEBUGFLAGS  = -g
OPTFLAGS= -O3
WFLAG   = -Wall -m64
LPJFLAGS  = -DUSE_RAND48 -DUSE_MPI -DSAFE -DWITH_FPE -DUSE_NETCDF -DUSE_UDUNITS -DPERMUTE -DSTRICT_JSON
O       = o
A       = a
E       =
AR      = ar
ARFLAGS = r
RM      = rm
RMFLAGS = -f
LIBS    = -lm -lnetcdf -ludunits2 -ljson-c
LINKMAIN= mpicc
LINK    = cc -m64
MKDIR   = mkdir -p
SLASH   = /
CFLAGS  = $(WFLAG) $(LPJFLAGS)  -Werror $(OPTFLAGS)
LNOPTS  = $(WFLAG) $(OPTFLAGS) -o
LPJROOT = /HOME/lpjml-workstation/LPJmL`

please  help me and give me some advices, thanks!

**Comment by cmueller-pik** [comment]
This is a new question and should have become a new issue.
I cannot understand the Chinese signs in your output, but it looks like the `-Werror` option caught a compiler warning and turned it into an error, namely that [fpc_obs](https://github.com/PIK-LPJmL/LPJmL/blob/383a0c510153a0a9f1b7a29f2694cfc1476a919d/src/lpj/establishmentpft.c#L85) may be used uninitilized. 
You can fix that by adding 
```code
fpc_obs = 0;
```
in line [77](https://github.com/PIK-LPJmL/LPJmL/blob/383a0c510153a0a9f1b7a29f2694cfc1476a919d/src/lpj/establishmentpft.c#L77) just before or after the 
```code
fpc_obs_cor = 1;
```

**Comment by cmueller-pik** [comment]
This is yet another question. Please open a new issue for new questions.
